### ISSUE TITLE
Pressing the shortcut key has no effect

### ISSUE THREAD

**Issue by 2919193553** [glitchifyed/quick-elytra#1]
@glitchifyed # # #

**Comment by glitchifyed** [comment]
to the config?

**Comment by 2919193553** [comment]
> 到配置？
I tried any version, press the default shortcut key has no effect, modify the shortcut key is useless, is I use the wrong way...

**Comment by glitchifyed** [comment]
i dont understand your broken google translated english

**Comment by 2919193553** [comment]
EQUIP TOTEM and SWAP ELYTRA Press the shortcut keys without any effect

**Comment by glitchifyed** [comment]
other mods might be interferring

**Comment by 2919193553** [comment]
> other mods might be interferring
Just install your mod and Cloth-config
