### ISSUE TITLE
keybind change crash

### ISSUE THREAD

**Issue by LordEnder-Kitty** [glitchifyed/quick-elytra#2]
it just crashes randomly when you change the keybinds to anything other then none.
i didn't download the wrong version or anything, its the same exact version and mod file that ive been using for months. and i didn't update or add any mods sense the last time it worked fine. i tried updating fabric and the fabric api, neither did anything.

**Comment by glitchifyed** [comment]
did you add any other mods?

**Comment by sudapeople** [comment]
https://i.imgur.com/eZa7z2g.png

This is a list of Multimc Fabric mode I am currently using. I used shortcuts, but Elytra and armor do not change automatically. Shortcuts are not used.

**Comment by glitchifyed** [comment]
As far as I have tested, the mod has worked for me. For now, I would suggest looking at alternatives to the mod.
