### ISSUE TITLE
Totem Keybind Not Working

### ISSUE THREAD

**Issue by MasterProVDX** [glitchifyed/quick-elytra#3]
Even on the default keybind, it isn't working

**Comment by glitchifyed** [comment]
I have tested the mod many times and have never had the issue. Are there any more details you can give me?

**Comment by MasterProVDX** [comment]
well, i've tried to make it work, i have a lot of other mods, let me try with only your mod-

**Comment by MasterProVDX** [comment]
hmm, it works, let me try with a bunch of more.

**Comment by MasterProVDX** [comment]
well, idk, will try something tomorrow

**Comment by glitchifyed** [comment]
The issues seem to be very inconsistent.

**Comment by Malysh25** [comment]
Hello. I also have such a problem

**Comment by glitchifyed** [comment]
Can you tell me specifically what isn't working properly? It's impossible to fix an issue that nobody explains to me.

**Comment by Malysh25** [comment]
When I press the hotkey, nothing happens. The totem is not taken in the 2nd hand. Unfortunately, I can't provide more information.

**Comment by glitchifyed** [comment]
If you're using version 1.0.0 of the mod, the totem hotkey will not work because it wasn't implemented until version 2.0.0. If that doesn't work for you, try updating your Minecraft version to 1.20.x and downloading my new mod Quick Hotkeys instead. https://www.github.com/glitchifyed/quick_hotkeys
